import React, { useState, useEffect } from 'react';
import Header from './components/Header';
import Footer from './components/Footer';
import Chatbot from './components/Chatbot';
import './styles/index.css';
import logo from './assets/logo.png';

const App = () => {
  // Load theme preference from localStorage
  const [darkMode, setDarkMode] = useState(() => {
    return localStorage.getItem('theme') === 'dark';
  });

  const toggleTheme = () => {
    setDarkMode(prevMode => {
      const newMode = !prevMode;
      localStorage.setItem('theme', newMode ? 'dark' : 'light'); // Save preference
      return newMode;
    });
  };

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark-theme');
    } else {
      document.documentElement.classList.remove('dark-theme');
    }
  }, [darkMode]);

  return (
    <div className="app-container">
      <Header darkMode={darkMode} toggleTheme={toggleTheme} logo={logo} />
      
      <main className="main-content">
        <div className="chatbot-layout">
          <div className="chat-history">
            <h3>Chat History</h3>
            <div className="history-messages">
              <div className="message bot">Hello! How can I assist you today?</div>
              <div className="message user">What is revenue?</div>
              <div className="message bot">Revenue is the total income generated by a company from its operations.</div>
            </div>
          </div>

          <div className="chat-window">
            <Chatbot darkMode={darkMode} />
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default App;
